name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4          
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag registry-1.docker.io/edomsha/esb2hadb:latest
    - name: push docker image
      run: docker push registry-1.docker.io/edomsha/esb2hadb:latest
